language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

env:
  - SYMFONY_VERSION=2.5.*

matrix:
  allow_failures:
    - php: 5.3
    - env: SYMFONY_VERSION=dev-master
    - php: hhvm
  include:
    - php: 5.5
      env: SYMFONY_VERSION=2.3.*
    - php: 5.5
      env: SYMFONY_VERSION=2.4.*
    - php: 5.5
      env: SYMFONY_VERSION=dev-master

before_script:
  - composer self-update
  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --prefer-source
  - vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: phpunit --coverage-text

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
